[package]
name = "yapppwn"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
hwaddr = "0.1.7"
packet = "0.1.4"
pnet = "0.35.0"

[dev-dependencies]
pcap = "2.0.0"

[[bin]]
name = "yapppwn"
path = "src/main.rs"
