[package]
name = "yapppwn"
version = "0.1.1"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
packet = "0.1.4"
pnet = "0.35.0"

[dev-dependencies]
pcap = "2.0.0"

[[bin]]
name = "yapppwn"
path = "src/main.rs"
